name: CI
on: 
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: HIE Build for ${{ matrix.os }}, GHC ${{ matrix.ghc }}, glibc ${{ matrix.glibc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ ubuntu-latest, macos-latest ]
        #ghc: [ "8.6.5", "8.8.3" ]
        #glibc: [ "2.27", "2.30" ]
        os: [ ubuntu-latest ]
        ghc: [ "8.8.3" ]
        glibc: [ "2.30" ]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@09c0620ab018415cbf1e6792e1f415cf892879b5
      with:
        name: all-hies
        extraPullNames: iohk
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Make sure materializations are up-to-date
      run: |
        nix-build ci.nix -A materialize --argstr ghcVersion ${{ matrix.ghc }} --argstr glibcVersion ${{ matrix.glibc }}
        ./result
        # Fails if there are any changes
        if ! [[ -z "$(git status --porcelain)" ]]; then
          echo "The materialization script made some changes:" >&2
          git status
          echo "Run \$(nix-build ci.nix -A materializeScript) to apply them" >&2
          exit 1
        fi
        echo "Materialization files up-to-date" >&2
    - name: Build HIE
      run: |
        nix-build ci.nix -A combined --argstr ghcVersion ${{ matrix.ghc }} --argstr glibcVersion ${{ matrix.glibc }}

  template_haskell-nix:
    name: Haskell.nix template for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        #os: [ ubuntu-latest, macos-latest ]
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: all-hies
        extraPullNames: iohk
    - name: Entering nix-shell
      run: |
        cd templates/haskell.nix
        nix-shell --run "echo Successfully entered nix-shell"
    - name: Call HIE
      run: |
        nix-shell --run "hie"
    - name: Search hoogle
      run: |
        nix-shell --run "hoogle fromMaybe" | grep Data.Maybe
    - name: Build and run with cabal
      run: |
        nix-shell --run "cabal run"
    - name: Build and run with Nix
      run: |
        nix-build
        ./result/bin/all-hies-template

  template_nixpkgs-infra:
    name: Nixpkgs infra template for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        #os: [ ubuntu-latest, macos-latest ]
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: all-hies
        extraPullNames: iohk
    - name: Entering nix-shell
      run: |
        cd templates/nixpkgs-infra
        nix-shell --run "echo Successfully entered nix-shell"
    - name: Call HIE
      run: |
        nix-shell --run "hie"
    - name: Search hoogle
      run: |
        nix-shell --run "hoogle fromMaybe" | grep Data.Maybe
    - name: Build and run with cabal
      run: |
        nix-shell --run "cabal run"
    - name: Build and run with Nix
      run: |
        nix-build
        ./result/bin/all-hies-template
